# Generated by Django 5.2.2 on 2025-06-07 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='کد پرسنلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('idle', 'بیکار'), ('absent', 'غایب')], max_length=10, verbose_name='وضعیت')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Detection_App.person', verbose_name='فرد')),
            ],
        ),
    ]
